server:
  port: 8081
spring:
  application:
    name: service-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}